
CREATE TABLE clientes_pj1 (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    email VARCHAR2(100),
    telefone NUMBER
);

COMMIT;

-- Script: create_tables.sql
-- Projeto: Controle de Estoque com Notificações Automáticas

-- Criação da tabela de fornecedores
CREATE TABLE fornecedores_pj1 (
    id_fornecedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(100) NOT NULL,
    cnpj          VARCHAR2(20),
    contato       VARCHAR2(100)
);

-- Criação da tabela de produtos
CREATE TABLE produtos_pj1 (
    id_produto         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome               VARCHAR2(100) NOT NULL,
    quantidade_estoque NUMBER DEFAULT 0,
    estoque_minimo     NUMBER DEFAULT 10,
    id_fornecedor      NUMBER,
    CONSTRAINT fk_produto_fornecedor FOREIGN KEY (id_fornecedor)
        REFERENCES fornecedores(id_fornecedor)
);

-- Criação da tabela de movimentações de estoque
CREATE TABLE movimentacao_estoque_pj1 (
    id_movimentacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto      NUMBER NOT NULL,
    tipo            VARCHAR2(10) CHECK (tipo IN ('ENTRADA', 'SAIDA')),
    quantidade      NUMBER NOT NULL,
    data_movimentacao DATE DEFAULT SYSDATE,
    CONSTRAINT fk_movimentacao_produto FOREIGN KEY (id_produto)
        REFERENCES produtos(id_produto)
);
